services:
  - type: web
    name: draftq-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers=2 --threads=4 --timeout=120
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: draftq-redis
          property: connectionString
      - key: S3_BUCKET
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: us-east-1
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SENDER_EMAIL
        sync: false
      - key: OCRSPACE_API_KEY
        sync: false

  - type: worker
    name: draftq-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: rq worker -u $REDIS_URL draftq-queue
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: draftq-redis
          property: connectionString
      - key: S3_BUCKET
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: us-east-1
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SENDER_EMAIL
        sync: false
      - key: OCRSPACE_API_KEY
        sync: false

databases:
  - name: draftq-redis
    plan: free
    ipAllowList: []   # allow web+worker