# force redeploy - dummy change
services:
  # ---------------------------
  # Web backend (Flask)
  # ---------------------------
  - type: web
    name: draftq-backend
    env: python
    region: oregon
    plan: starter
    autoDeploy: true
    buildCommand: |
  pip install --upgrade pip setuptools wheel
  pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /health
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: draftq-redis
          property: connectionString
      - key: PYTHONUNBUFFERED
        value: "1"

      # ==== App secrets (values set in dashboard; not synced from git) ====
      - key: S3_BUCKET
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SENDER_EMAIL
        sync: false
      - key: OCRSPACE_API_KEY
        sync: false

  # ---------------------------
  # Background worker (RQ)
  # ---------------------------
  - type: worker
    name: draftq-worker
    env: python
    region: oregon
    plan: starter
    autoDeploy: true
    buildCommand: |
  pip install --upgrade pip setuptools wheel
  pip install -r requirements.txt
    startCommand: rq worker -u $REDIS_URL default
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: draftq-redis
          property: connectionString

      # same secrets as backend (values set in dashboard)
      - key: S3_BUCKET
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SENDER_EMAIL
        sync: false
      - key: OCRSPACE_API_KEY
        sync: false

  # ---------------------------
  # Redis (already exists, name must match)
  # ---------------------------
  - type: redis
    name: draftq-redis
    region: oregon
    plan: starter
    ipAllowList: []